apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-idp-declarative
  namespace: argocd
spec: 
  project: default 
  syncPolicy:
    automated:
      enabled: true
  source: 
    repoURL: https://github.com/fabio-teichmann/ple-1-internal-dev-platform-mini.git
    targetRevision: HEAD 
    path: apps/sample-app 
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
