apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: test-app-service-template
  namespace: argocd
spec: 
  project: default 
  syncPolicy:
    automated:
      enabled: true
  source: 
    repoURL: https://github.com/fabio-teichmann/ple-1-internal-dev-platform-mini.git
    targetRevision: HEAD 
    path: manifests/sample-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
EOF 
